# Generated by Django 5.0 on 2026-04-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='swipe',
            name='is_superlike',
            field=models.BooleanField(default=False),
        ),
    ]
