# Generated by Django 5.0 on 2026-04-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_message_is_deleted_message_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='hidden_by_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
